class AutomatedTuningModel:
    def __init__(self):
        self.unique_id = ""
        self.product = ""
        self.condensed_form = ""
        self.location_group = ""
        self.salt_value = ""
        self.price_up_active_flag = ""
        self.price_up_measurement_level = ""
        self.price_up_concentration = ""
        self.price_up_magnitude = ""
        self.price_up_realization = ""
        self.price_up_min_win_rate_diff = ""
        self.price_up_sig_level = ""
        self.price_up_power = ""
        self.price_up_obs_req = ""
        self.price_down_active_flag = ""
        self.price_down_measurement_level = ""
        self.price_down_concentration = ""
        self.price_down_magnitude = ""
        self.price_down_realization = ""
        self.price_down_min_win_rate_diff = ""
        self.price_down_sig_level = ""
        self.price_down_power = ""
        self.price_down_obs_req = ""
