class ProductModel:
    def __init__(self):
        self.unique_id = ""
        self.rc_mapping = ""
        self.material = ""
        self.bellwether_material = ""
        self.product_name = ""
        self.form = ""
        self.index = ""
        self.bellwether_base_cost = ""
        self.market_movement_adder = ""
        self.percent_adjustment = ""
        self.dollar_adjustment = ""
        self.modeled_cost = ""
        self.unit_handling_cost = ""
        self.per_ton_packaging_cost = ""
        self.per_ton_stocking_cost = ""
        self.material_description = ""
        self.exchange_rate = ""
